---
- name: install macvim
  homebrew_cask:
    name=macvim
    state=present

- name: install Vundle
  git:
      repo: https://github.com/VundleVim/Vundle.Vim.git
      dest: ~/.vim/bundle/Vundle.vim

- name: install Vundle plugins
  shell: vim -c VundleUpdate -c quitall > /dev/null
- name: install editorconfig
  homebrew:
    name: editorconfig
    state: present
