---
language: objective-c
before_install:
- sudo easy_install pip
install:
- sudo pip install ansible
script:
- echo localhost > inventory
- ansible-playbook --syntax-check site.yml
- ansible-playbook site.yml -vvvv
 
